### ISSUE TITLE
generator-yyweb/app/templates/module/index/index.html 中 resetScreen 方法的问题

### ISSUE THREAD

**Issue by jiazheng** [erichmlyh/generator-yyweb#1]
在 iPhone 全屏手机中，webview 当中获取的 window.innerHeight 高度没有包括底部的安全区域。导致页面无法撑满整个屏幕高度。

**Comment by erichmlyh** [comment]
https://github.com/erichmlyh/generator-yyweb/commit/2cb1d314be76f4a2401cb9259d198e3c2040cabb
用outerHeight代替innerHeight了

**Comment by erichmlyh** [comment]
> 在 iPhone 全屏手机中，webview 当中获取的 window.innerHeight 高度没有包括底部的安全区域。导致页面无法撑满整个屏幕高度。

https://github.com/erichmlyh/generator-yyweb/commit/2cb1d314be76f4a2401cb9259d198e3c2040cabb
用outerHeight代理innerHeight了
